### ISSUE TITLE
Can you share your configuration for the dark mode dictionary extraPane from the your landing page?

### ISSUE THREAD

**Issue by ankidoc** [mr-pennyworth/alfred-extra-pane#11]
I'm not really into coding but could you share this in an easy way?

**Comment by mr-pennyworth** [comment]
@ankidoc apologies, I can't find that theme anymore.
This is the closest I have: 
[Round Snazzy Dark.zip](https://github.com/mr-pennyworth/alfred-extra-pane/files/14466953/Round.Snazzy.Dark.zip)
