### ISSUE TITLE
How do I uninstall this program?

### ISSUE THREAD

**Issue by llity** [mr-pennyworth/alfred-extra-pane#12]
Need to provide uninstall method      
![image](https://github.com/mr-pennyworth/alfred-extra-pane/assets/11771112/25492298-3ffd-48d8-8503-fb5edb56c28d)

**Comment by mr-pennyworth** [comment]
Thanks for the bug report @llity!
Can you provide step-by-step info on what you did?
(I'm not sure I understand the problem by looking at the screenshot)

To Uninstall:
1. Open Activity Monitor, kill any `AlfredExtraPane` if running.
2. Drag `AlfredExtraPane` to trash.
3. Empty trash.

**Comment by daaaaaaaaaniel** [comment]
Can you please explain the proper way to uninstall?
