### ISSUE TITLE
Does not show on Apple Silicon 

### ISSUE THREAD

**Issue by willdhorn** [mr-pennyworth/alfred-extra-pane#14]
I just downloaded the newest release alfred-better-dictionaries, but I've been unable to get the extra pane to show up at all. I can see that the application shows up in Activity Monitor, and I can even watch the cpu usage go up when I use the workflow. 

M2 Macbook
macOS 13.6.1
Alfred 5.5 [2257]
alfred-better-dictionaries 0.2.14

**Comment by willdhorn** [comment]
Quitting Alfred and restarting it gets the pane to show up, but it's not matching the theme properly
<img width="600" alt="Screenshot 2024-06-27 at 1 23 00 PM" src="https://github.com/mr-pennyworth/alfred-extra-pane/assets/88556285/82022604-f645-4265-a588-ee375871997f">

**Comment by willdhorn** [comment]
Closing AlfredExtraPane from Activity Monitor got the panel to show up and be readable, but it reverted back to gray after a couple lookups. I closed AlfredExtraPane again, which fixed it, then I tried to break it intentionally, but couldn't. Finally, as I was trying to take a screenshot (since it still wasn't matching and looked the same regardless of theme), it reverted to gray and has stayed that way. Now, restarting either Alfred or AlfredExtraPane seems to have no effect.

**Comment by mr-pennyworth** [comment]
Thanks for the report @willdhorn!
Strange bug! 🤔
Can you share the theme with me?
(Right click on the theme, and then `Export as File...`)
<img width="445" alt="image" src="https://github.com/mr-pennyworth/alfred-extra-pane/assets/74945464/dda06c1e-f268-43e2-8e1d-72d11fdbe56f">

**Comment by willdhorn** [comment]
Sure! Github won't let me attach it as file, but here's the json:
 
```json
{
  "alfredtheme" : {
    "result" : {
      "textSpacing" : 4,
      "subtext" : {
        "size" : 16,
        "colorSelected" : "#00C0ABFF",
        "font" : "Avenir Light Oblique",
        "color" : "#96ACB777"
      },
      "shortcut" : {
        "size" : 23,
        "colorSelected" : "#FF286DFF",
        "font" : "Avenir Black",
        "color" : "#ACBEC5FF"
      },
      "backgroundSelected" : "#1B272CFF",
      "text" : {
        "size" : 24,
        "colorSelected" : "#00D5BDFF",
        "font" : "Avenir Medium",
        "color" : "#ACBEC5FF"
      },
      "iconPaddingHorizontal" : 14,
      "roundness" : 10,
      "paddingVertical" : 4,
      "iconSize" : 40
    },
    "search" : {
      "backgroundSelected" : "#577E8CFF",
      "paddingHorizontal" : 14,
      "spacing" : 9,
      "text" : {
        "size" : 30,
        "colorSelected" : "#FEFFFFFF",
        "font" : "GoMono Nerd Font",
        "color" : "#FEFFFFFF"
      },
      "background" : "#1B272CFF",
      "roundness" : 10,
      "paddingVertical" : 4
    },
    "window" : {
      "color" : "#1836414F",
      "paddingHorizontal" : 5,
      "width" : 673,
      "borderPadding" : 0,
      "borderColor" : "#131313FF",
      "blur" : 0,
      "roundness" : 14,
      "paddingVertical" : 5
    },
    "credit" : "Will",
    "visualEffectMode" : 2,
    "separator" : {
      "color" : "#223238FF",
      "thickness" : 1
    },
    "scrollbar" : {
      "color" : "#FF286DFF",
      "thickness" : 2
    },
    "name" : "MaterialLike"
  }
}

**Comment by mr-pennyworth** [comment]
Thanks @willdhorn!
I installed the theme and I see the same issue that you're having.
The extra pane doesn't support transparency.
Lemme see if I can (from most preferred to least preferred):
1. Add support for transparency.
2. Display a warning when a transparent theme is detected.
3. Add the limitation to the readme.

**Comment by mr-pennyworth** [comment]
Fixed in https://github.com/mr-pennyworth/alfred-extra-pane/releases/tag/0.1.7

**Comment by mr-pennyworth** [comment]
Using this place as an image pastebin 🤷🏻‍♂️
<img width="754" alt="image" src="https://github.com/user-attachments/assets/828e8576-d309-4388-b5f3-fdb29e319442">
<img width="716" alt="image" src="https://github.com/user-attachments/assets/3def3c4c-a6c1-4602-b9fb-7c744531ccd2">
<img width="695" alt="image" src="https://github.com/user-attachments/assets/7fe7eafc-4e38-4646-bd34-b4d7b598d43f">
<img width="687" alt="image" src="https://github.com/user-attachments/assets/4813ef43-6737-408c-a092-42bc64e357de">
<img width="703" alt="image" src="https://github.com/user-attachments/assets/62f21d8c-8216-429c-a968-74c48d0db56b">

**Comment by snam24** [comment]
Hi @mr-pennyworth, can you please share the workflows on the screenshots that work with Alfred ExtraPane? They look awesome!

**Comment by mr-pennyworth** [comment]
@snam24 those screenshots are for "Google Search" workflow.
For details, check out the tutorial: https://github.com/mr-pennyworth/alfred-extra-pane#tutorial-search-google-as-you-type

Here's the workflow: 
[Google Search.zip](https://github.com/user-attachments/files/16275707/Google.Search.zip)
