### ISSUE TITLE
[Feature request] Progress indicator while loading page

### ISSUE THREAD

**Issue by ghost** [mr-pennyworth/alfred-extra-pane#19]
I often click around in AlfredExtraPane, and it would be really helpful to have a progress indicator appear after clicking a link. This would 1) confirm that the link can actually be opened in AlfredExtraPane, and 2) show the user how long the page is taking to load. It could be something subtle, like what we see here on GitHub.

![image](https://github.com/user-attachments/assets/b0fa0529-65fe-4e27-b24b-79703f404fb2)

**Comment by mr-pennyworth** [comment]
I won't be able to get to this. Especially since this doesn't figure as a use case I find personally useful. Closing as the reporter seems to also have gone. If someone sends a PR, will be happy to merge 😇
