### ISSUE TITLE
Fix width / transparency 

### ISSUE THREAD

**Issue by TheSecEng** [mr-pennyworth/alfred-extra-pane#2]
https://github.com/mr-pennyworth/alfred-extra-pane/blob/017d651523398a22568bc6ecabf82b73f7811dc6/AlfredExtraPane/main.swift#L127

This should take alfred.MinX and add alfreds width to it. So that you only draw your program to the right side of alfred. We don't want to draw behind alfred.

```swift
x: alfred.minX + alfred.Width
```

**Comment by mr-pennyworth** [comment]
Thanks @TheSecEng for the report! 🙂
I think that's a question of preference.

I prefer the first one, while your suggested change will lead to the second one:
![full](https://user-images.githubusercontent.com/74945464/103366626-2431a200-4ae9-11eb-8ad0-96edbd5cb51e.png)
![half](https://user-images.githubusercontent.com/74945464/103366641-28f65600-4ae9-11eb-8b56-c3544f7e091c.png)

**Comment by TheSecEng** [comment]
Could we just redraw the height of the extra pane as Alfreds size changes ? I think I’ll spin off and iterate in this personally. This is a great project. One that I’ve been wanting to do for some time but side tracked by to many competing priorities

kudos to you

**Comment by mr-pennyworth** [comment]
> Could we just redraw the height of the extra pane as Alfred's size changes?

I had tried that, but didn't like how it looked when there are only 2-3 results. The extra pane looked way too short for my taste.

>  I think I’ll spin off and iterate in this personally.

Looking forward to it! 😃 

Thanks for the encouraging words! 😊
