### ISSUE TITLE
[Feature request] Zoom within AlfredExtraPane using trackpad (pinch)

### ISSUE THREAD

**Issue by glowacky** [mr-pennyworth/alfred-extra-pane#22]
If possible, please add support for zooming within AlfredExtraPane (using trackpad pinch gestures, etc.). Thanks!

**Comment by mr-pennyworth** [comment]
Nice suggestion @glowacky!

I wasn't able to figure out how to support pinch-and-zoom even when the pane is not in focus.
However, it was straightforward to support it when the user has already clicked on the pane.
Hope this helps you at least partially!

Feel free to send in a patch if you are able to figure out how to support it without needing to click on the pane first :)

**Comment by glowacky** [comment]
it helps indeed, thank you!
