### ISSUE TITLE
HTML Panel cannot control with the "puzzle" style captcha

### ISSUE THREAD

**Issue by olivergiangvu** [mr-pennyworth/alfred-extra-pane#23]
Hi,

![CleanShot 2024-08-07 at 16 10 25](https://github.com/user-attachments/assets/fd97a94e-878f-4441-a8d2-c8a02bbad004)
I jumped into another issue after testing the search worflow for this url **https://shopee.vn/search?keyword=** 

Firstly I can't log into to my account from HTML Panel then finnally some how logged in it always stuck at the captcha as I cant drag the puzzle with mouse crusor.

**Comment by mr-pennyworth** [comment]
@olivergiangvu is it the case that even after you click and drag the arrow on the captcha nothing happens?
(In the video, I only see the mouse go over the arrow, and that's all)

Unfortunately, I can't debug this as I don't have account on the site and it won't let me create a new account with a throwaway email address (it only accepts phone numbers, or google login)

**Comment by olivergiangvu** [comment]
> @olivergiangvu is it the case that even after you click and drag the arrow on the captcha nothing happens?
> 
> (In the video, I only see the mouse go over the arrow, and that's all)
> 
> 
> 
> Unfortunately, I can't debug this as I don't have account on the site and it won't let me create a new account with a throwaway email address (it only accepts phone numbers, or google login)

Hi @mr-pennyworth,
Yea, that what happened, I can drag the arrow with mouse click.
I created a dumb account with my unused gmail account. Let me know where I can DM you to send   the credentials.

**Comment by olivergiangvu** [comment]
Suddenly after restar the HTML Panel work for this site now 😂
![CleanShot 2024-08-09 at 17 54 30](https://github.com/user-attachments/assets/fa3ee09f-31ad-48d7-b725-11c487fe1ef0)

**Comment by mr-pennyworth** [comment]
great that it is working now!
I can imagine that all the browserlike functionality has issues.
since the main intention for the extra pane is for displaying additional stuff that can't be displayed in Alfred, and not be a "mini browser", I probably won't be prioritizing the corner cases...
