### ISSUE TITLE
The Sample Google search as you type script sample not work anymore on macOS 15.0

### ISSUE THREAD

**Issue by olivergiangvu** [mr-pennyworth/alfred-extra-pane#26]
q="$1"

function urlencode {
  echo -n "$1" \
   | /usr/bin/python3 -c "import sys, urllib.parse; print(urllib.parse.quote_plus(sys.stdin.read()),end='')"
}

url_q=$(urlencode "$1")

cat << EOF
{"items" : [
  {"title": "Search $q",
   "subtitle": "using google.com",
   "arg": "https://www.google.com/search?q=$url_q",
   "quicklookurl": "https://www.google.com/search?q=$url_q"}
]}
EOF

This sample not work anymore on the new macOS 15.0 update. Thanks!

**Comment by olivergiangvu** [comment]
Found out why - the python location was changed since the OS updated - FIXED- Thanks!

**Comment by mr-pennyworth** [comment]
@olivergiangvu what's the python path on macOS 15 by the way?

**Comment by olivergiangvu** [comment]
> @olivergiangvu what's the python path on macOS 15 by the way?

for my case 
function urlencode {
  echo -n "$1" \
   | /opt/homebrew/bin/python3 -c "import sys, urllib.parse; print(urllib.parse.quote_plus(sys.stdin.read()),end='')"
}
as I installed it by homebrew
