### ISSUE TITLE
Extremely buggy and inefficient on Apple Silicon

### ISSUE THREAD

**Issue by SoloUnity** [mr-pennyworth/alfred-extra-pane#3]
Alfred extra pane hangs for over 20 seconds on first launch while being complete out of alignment. It is also always at 5-15% cpu usage despite being rarely invoked, causing a large than expected drain on battery.

**Comment by mr-pennyworth** [comment]
@SoloUnity I wonder whether the overhead is coming from the python scripts 🤔
Or maybe because of the mouse / keyboard tracking?
I have now removed all of those components, making the footprint smaller.
I don't have a M1 mac to try this on though 😞
Do give the new release a whirl if you'd like 😇
