### ISSUE TITLE
Python error: no such file or directory

### ISSUE THREAD

**Issue by kenanmike** [mr-pennyworth/alfred-extra-pane#5]
I'm getting the following error despite having python & python3 installed on my system. How do I change where AlfredExtraPane looks for python? In Monterey 12.3.1 it should be /usr/local/bin/python not usr/bin/python.

> ./search.sh: AlfredExtraPane.app/Contents/Resources/scripts/alfred-extra-pane: /usr/bin/python: bad interpreter: No such file or directory

**Comment by mr-pennyworth** [comment]
Thanks for the bug report @kenanmike!
`AlfredExtraPane` no longer needs any python, so this should be fixed now 😊
