### ISSUE TITLE
FR: rounded corners?

### ISSUE THREAD

**Issue by chrisgrieser** [mr-pennyworth/alfred-extra-pane#7]
Mostly an aesthetic thing, but would it be possible for the extra pane to have rounded corners, like with the Alfred window itself? My Alfred window having rounded corners and the pane having sharp corners feels somewhat visually unpleasing.
![Pasted image 2024-02-23 at 22 08 35@2x](https://github.com/mr-pennyworth/alfred-extra-pane/assets/73286100/60311ae2-166c-4050-a4ac-f3430be2b616)

(btw, only noticed today that it works super well with my workflow for Reddit! That was a welcome surprise, thank you so much for this :) )

**Comment by mr-pennyworth** [comment]
Great suggestion @chrisgrieser!
With b4c6090, now the pane's rounded corners should match Alfred's
<img width="975" alt="image" src="https://github.com/mr-pennyworth/alfred-extra-pane/assets/74945464/aa67611f-bf9b-46b5-bee3-14c860a4ff98">
