### ISSUE TITLE
Mute extra-pane, e.g. for video URLs

### ISSUE THREAD

**Issue by chrisgrieser** [mr-pennyworth/alfred-extra-pane#9]
Using some workflows, such as the [Chrome History search](https://alfred.app/workflows/acidham/chromium-bookmarks-and-history-search/), results in the extra-pane opening a URL to a video site like youtube. 

Not only do they auto-play (which isn't that big of a deal), but they also by default have audio. Suddenly getting full-blown sounds while going through your browser history is really a bit irritating 🙈

I think as a preview-window, it'd make sense to have any opened URLs be muted?

**Comment by mr-pennyworth** [comment]
Good point @chrisgrieser!
I have disabled autoplay for now. Ideally, it should be configurable. I'd be happy to merge patches to make it so :)

**Comment by chrisgrieser** [comment]
thank you 😊 

I may create a lot of Alfred workflows, but I have zero knowledge of swift, otherwise I'd have made a bunch of PRs already 😅

**Comment by mr-pennyworth** [comment]
@glowacky here you go: 09b9cc4
This should be part of the `0.2.1` build

**Comment by glowacky** [comment]
@mr-pennyworth thank you!
